import React from "react";
import { DM_Sans, Russo_One } from "next/font/google";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BodyWrapper from "@/components/BodyWrapper";

export const metadata = {
  title: "Tanuki",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dmsans",
});

const russo = Russo_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-russo",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BodyWrapper className={`${dmSans.variable} ${russo.variable} font-sans`}>
        <Header />
        {children}
        <Footer />
      </BodyWrapper>
    </html>
  );
}
